### ISSUE TITLE
win 报错

### ISSUE THREAD

**Issue by gongxianjin** [xiaodingding/iotfast#8]
Cannot remove temporary socket:  remove C:\Users\ADMINI~1\AppData\Local\Temp/iotfast_plugin: The system cannot find the file specified.
using proto:unix, netAddr:C:\Users\ADMINI~1\AppData\Local\Temp/iotfast_plugin ,err:listen unix C:\Users\ADMINI~1\AppData\Local\Temp/iotfast_plugin: socket: An address incompatible with the requested protocol was used., creat server failed
using proto:unix, netAddr:C:\Users\ADMINI~1\AppData\Local\Temp/iotfast_plugin ,err:listen unix C:\Users\ADMINI~1\AppData\Local\Temp/iotfast_plugin: socket: An address incompatible with the requested protocol was used., creat server failed
using proto:unix, netAddr:C:\Users\ADMINI~1\AppData\Local\Temp/iotfast_plugin ,err:listen unix C:\Users\ADMINI~1\AppData\Local\Temp/iotfast_plugin: socket: An address incompatible with the requested protocol was used., creat server failed
using proto:unix, netAddr:C:\Users\ADMINI~1\AppData\Local\Temp/iotfast_plugin ,err:listen unix C:\Users\ADMINI~1\AppData\Local\Temp/iotfast_plugin: socket: An address incompatible with the requested protocol was used., creat server failed
server plugin start successful
panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x28 pc=0x10db6e9]

goroutine 59 [running]:
github.com/xiaodingding/iotfast/plugin/server.(*server).serveTCP.func1(0x0, 0x0, 0xc000bd8000)
        E:/src/iotfast/plugin/server/server.go:231 +0x29
panic(0x14a8a00, 0x279f180)
        D:/ProgramFiles/Go/src/runtime/panic.go:965 +0x1c7
github.com/xiaodingding/iotfast/plugin/server.(*server).serveTCP(0xc000bd8000, 0x0, 0x0)
        E:/src/iotfast/plugin/server/server.go:239 +0x133
github.com/xiaodingding/iotfast/plugin/server.(*server).Start(0xc000bd8000)
        E:/src/iotfast/plugin/server/server.go:385 +0x3cf
github.com/xiaodingding/iotfast/internal/cmd.glob..func3(0x1e25fd8, 0xc000146870, 0xc000134700, 0x11, 0x0)
        E:/src/iotfast/internal/cmd/cmd.go:93 +0x65
created by github.com/xiaodingding/iotfast/internal/cmd.glob..func4
        E:/src/iotfast/internal/cmd/cmd.go:105 +0xf9

**Comment by jackeyjin2002** [comment]
please run under Windows 10, AF_UNIX is not support Windows 7(2008).

**Comment by xiaodingding** [comment]
哦哦，你可以不用unix协议
